### ISSUE TITLE
org.apache.lucene.index.IndexNotFoundException: no segments* file found in MMapDirectory

### ISSUE THREAD

**Issue by pallapothurameshbabu** [cominvent/solr-tools#2]
Hi,

We are using upgradeindex.sh file to index 4.10 data to 6.6, facing below exception while doing that. Could you please help us on this.

Exception in thread "main" org.apache.lucene.index.IndexNotFoundException: no segments* file found in MMapDirectory@/var//solr-6.6.0/shard2/solr/cese/data/index.20171103115319432 lockFactory=org.apache.lucene.store.NativeFSLockFactory@506c589e: files: [_ka95.nvd, _ka95.si, _ka95_Lucene41_0.tim, _ka95_Lucene41_0.tip, _ka95_ory.del, _kajo.fnm, _kajo_Lucene41_0.doc, _kajo_Lucene41_0.pos, _kajo_Lucene41_0.tim, _kajo_Lucene41_0.tip, _kaw5.nvd, _kaw5.nvm, _lym9_iru.del, _m6s3.fdt, _m6s3.fdx, _n64l_d5n.del, _nrkh_amh.del, _oh1t.fdt, _oh1t.fdx, _p3nf_4ye.del, _p3nf_Lucene41_0.doc, _pq2n_1gv.del, _ps12.fnm, _ps12_nd.del, _pu4x.fnm, _pu4x_Lucene41_0.tim, _pu4x_Lucene41_0.tip, _pu4x_ap.del, _pw41_Lucene41_0.doc, _pw41_Lucene41_0.pos, _pyfu.fdx, _pyfu.nvd, _pyfu.nvm, _pyfu_Lucene41_0.doc, _q44p.fdt, _q44p.fdx, _q44p.nvd, _q44p.nvm, _q44p.si, _q44p_Lucene41_0.pos, _q481.fdt, _q481.fdx, _q481_Lucene41_0.doc, _q48l.fnm, _q48l_Lucene41_0.tim, _q48l_Lucene41_0.tip, _q48v.nvd, _q48v.nvm, _q48v_Lucene41_0.doc, _q48v_Lucene41_0.pos, _q495.fnm, _q495_Lucene41_0.pos, _q495_Lucene41_0.tim, _q495_Lucene41_0.tip, _q496.fnm, _q496_1.del, _q496_Lucene41_0.doc, _q497.fdt, _q497.fdx, _q497.nvd, _q497.nvm, _q497_Lucene41_0.tim, _q497_Lucene41_0.tip, _q498.fdt, _q498.fdx, _q498.nvd, _q498.nvm, _q498_Lucene41_0.tim, _q498_Lucene41_0.tip, _q499.nvd, _q499.nvm, _q499_1.del, _q49a_1.del, write.lock]
        at org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:502)
        at org.apache.lucene.index.CheckIndex.doCheck(CheckIndex.java:2595)
        at org.apache.lucene.index.CheckIndex.doMain(CheckIndex.java:2497)
        at org.apache.lucene.index.CheckIndex.main(CheckIndex.java:2423)
Exception in thread "main" org.apache.lucene.index.IndexNotFoundException: no segments* file found in MMapDirectory@/var//solr-6.6.0/shard2/solr/cese/data/index.20171103115319432 lockFactory=org.apache.lucene.store.NativeFSLockFactory@404b9385: files: [_q498_Lucene41_0.tim, _q48v.nvm, _q498.fdx, _ka95.nvd, _lym9_iru.del, _pq2n_1gv.del, _kajo.fnm, _pu4x_Lucene41_0.tim, _q496.fnm, _ka95_Lucene41_0.tip, _nrkh_amh.del, _q44p.fdx, _q499.nvm, _p3nf_Lucene41_0.doc, _q497.nvd, _q48l_Lucene41_0.tip, _kaw5.nvm, _pyfu.nvm, _q495.fnm, _q44p.nvd, _q497_Lucene41_0.tim, _ka95_ory.del, _oh1t.fdt, _ps12_nd.del, _pyfu.nvd, _q481_Lucene41_0.doc, _pw41_Lucene41_0.doc, _q49a_1.del, _q48v.nvd, _q48v_Lucene41_0.doc, _kajo_Lucene41_0.tim, _ps12.fnm, _q498.nvm, _q495_Lucene41_0.pos, _q48v_Lucene41_0.pos, _m6s3.fdt, _q497.fdt, _q498.nvd, _kajo_Lucene41_0.doc, _q498.fdt, _pw41_Lucene41_0.pos, _kaw5.nvd, _q48l.fnm, _q497.fdx, _q496_Lucene41_0.doc, _ka95.si, _ka95_Lucene41_0.tim, _q497.nvm, _pu4x_Lucene41_0.tip, _q497_Lucene41_0.tip, _q481.fdx, _pyfu.fdx, _q44p.fdt, _q498_Lucene41_0.tip, _p3nf_4ye.del, _oh1t.fdx, _q499.nvd, _q44p_Lucene41_0.pos, _q44p.nvm, _pu4x.fnm, _q495_Lucene41_0.tip, _q48l_Lucene41_0.tim, _q499_1.del, _pyfu_Lucene41_0.doc, _q44p.si, _kajo_Lucene41_0.tip, _kajo_Lucene41_0.pos, _q496_1.del, _q495_Lucene41_0.tim, _pu4x_ap.del, _n64l_d5n.del, _q481.fdt, _m6s3.fdx, write.lock]
        at org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:483)
        at org.apache.lucene.index.CheckIndex.doCheck(CheckIndex.java:2407)
        at org.apache.lucene.index.CheckIndex.doMain(CheckIndex.java:2309)
        at org.apache.lucene.index.CheckIndex.main(CheckIndex.java:2235)
- Empty index?

Thanks!!!

**Comment by janhoy** [comment]
Hi, have not seen this before. But can you look in `/var/solr-6.6.0/shard2/solr/cese/data/index.20171103115319432` and see if that index is completely empty? The path looks funny, could it be some stale index from an auto snapshot or something?

**Comment by janhoy** [comment]
Did you have any luck in upgrading your index?
